[package]
name = "alloy-example"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.3.6", features = ["providers"] }
eyre = { version = "0.6.12",features = ["default"] }
tokio = {version = "1.40.0", features = ["full"]}
